-- 商户表, 2017-5-9 add
create table merchant (
	id bigint (20) not null comment '商户id',
	userId bigint (12) comment '关系用户编号',
	merchantName varchar (200) comment '商户名称',
	merchantType int (2) comment '商户类型',
	cascadeLabel varchar (60) comment '级联标签',
	cascadeLevel int (3) comment '级联等级',
	parentId bigint (20) comment '父商户id',
	parentName varchar (200) comment '父商户名称',
	account varchar (60) comment '账号',
	roleIds varchar (200) comment '角色ids',
	roleNames varchar (400) comment '角色名称',
	contact varchar (200) comment '联系人',
	contactWay varchar (50) comment '联系方式',
	projectId bigint (20) comment '项目id',
	projectName varchar (50) comment '项目名称',
	priIndustryCode varchar (50) comment '一级行业id',
	priIndustry varchar (50) comment '一级行业',
	secIndustryCode varchar (50) comment '二级行业id',
	secIndustry varchar (50) comment '二级行业',
	provinceId bigint (8) comment '省id',
	province varchar (50) comment '省',
	cityId bigint (8) comment '市id',
	city varchar (50) comment '市',
	areaId bigint (8) comment '区县id',
	area varchar (50) comment '区县',
	locationFullName varchar (200) comment '地区全称',
	address varchar (200) comment '详细地址',
	storeType int (2) comment '销售点二级分类：1代表专营店、2代表自有厅、3代表其他',
	storeLevel int (2) comment '自有厅级别：1代表1级、2代表2级、3代表3级、4代表4级、5代表5级',
	storeStar int (2) comment '专营店星级：1代表1星、2代表2星、3代表3星、4代表4星、 5代表5星',
	storeScope int (2) comment '专营店类别：1代表社区店、2代表商圈店、3代表旗舰店、4代表其他',
	connectType varchar (20) comment '接入方式：chinanet代表chinanet接入、fatap代表胖ap接入、optical modem代表定制光猫接入、others代表其他',
	remark varchar (200) comment '备注',
	createDate varchar (25) comment '创建日期,示例：2017-01-19 09:50:27',
	updateDate varchar (25) comment '修改日期，示例：2017-01-19 09:50:27',
	status int (2) comment '状态 1：正常；9：注销',
	primary key (id)
);

-- 网络放通日志表, 2017-5-11 add
create table wifi_record (
	id bigint not null auto_increment comment '主键id',
	user_id bigint comment '用户id',
	merchant_id bigint comment '商户id',
	portal_url varchar (200) comment 'portal url',
	telphone varchar (11) comment '用户手机号码',
	device_id varchar(64) comment 'deviceId',
	dev_type varchar (10) comment '设备类型',
	token varchar (20) comment 'token',
	token_date datetime comment 'token生成时间',
	wifi_url varchar (100) comment '网络放通url',
	wifi_result varchar (30) comment '网络放通成功或失败的结果',
	wifi_date datetime comment '网络放通成功或失败的时间',
	error_info varchar (200) comment '失败原因',
	primary key (id)
);
